// <auto-generated />
using System;
using CareNet_System.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareNet_System.Migrations
{
    [DbContext(typeof(HosPitalContext))]
    [Migration("20250514210639_AhmedMig")]
    partial class AhmedMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareNet_System.Models.Bills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("insurance_id")
                        .HasColumnType("int");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<double>("total_amount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("patient_id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("CareNet_System.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Patients_num")
                        .HasColumnType("int");

                    b.Property<int>("employees_num")
                        .HasColumnType("int");

                    b.Property<string>("manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CareNet_System.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("dept_id")
                        .HasColumnType("int");

                    b.Property<int>("followUp_doctorID")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("room_num")
                        .HasColumnType("int");

                    b.Property<string>("treatment")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("dept_id");

                    b.HasIndex("followUp_doctorID")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CareNet_System.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("dept_id")
                        .HasColumnType("int");

                    b.Property<int>("experience_years")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personal_photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("seniority_level")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("dept_id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("CareNet_System.Models.Bills", b =>
                {
                    b.HasOne("CareNet_System.Models.Patient", "patient")
                        .WithMany("bills")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient");
                });

            modelBuilder.Entity("CareNet_System.Models.Patient", b =>
                {
                    b.HasOne("CareNet_System.Models.Department", "department")
                        .WithMany("patients")
                        .HasForeignKey("dept_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareNet_System.Models.Staff", "staff")
                        .WithOne("patients")
                        .HasForeignKey("CareNet_System.Models.Patient", "followUp_doctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("CareNet_System.Models.Staff", b =>
                {
                    b.HasOne("CareNet_System.Models.Department", "department")
                        .WithMany("staff")
                        .HasForeignKey("dept_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("CareNet_System.Models.Department", b =>
                {
                    b.Navigation("patients");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("CareNet_System.Models.Patient", b =>
                {
                    b.Navigation("bills");
                });

            modelBuilder.Entity("CareNet_System.Models.Staff", b =>
                {
                    b.Navigation("patients");
                });
#pragma warning restore 612, 618
        }
    }
}
